###
## getCiudadesList [Mostrar la ciudad de id 59 que no tiene habitantes ni equipos]
GET http://localhost:8090/api/v1/ciudades/59/info HTTP/1.1
Content-Type: application/json

###
## getCiudadesListOrderByName
GET http://localhost:8090/api/v1/ciudades/orden/desc HTTP/1.1
Content-Type: application/json

###
## getCiudadInfoById
GET http://localhost:8090/api/v1/ciudades/56/info HTTP/1.1
Content-Type: application/json



###
## getAllEquipos
GET http://localhost:8090/api/v1/equipos HTTP/1.1
Content-Type: application/json


###
## getAllCiudades
GET http://localhost:8090/api/v1/ciudades HTTP/1.1
Content-Type: application/json


###
## getAllJugadores
GET http://localhost:8090/api/v1/jugadores HTTP/1.1
Content-Type: application/json


###
## getAllPorteros
GET http://localhost:8090/api/v1/porteros HTTP/1.1
Content-Type: application/json

###
## getUsuarioInfo
GET http://localhost:8090/api/usuarios/byNickname/joserra HTTP/1.1
Content-Type: application/json



###########

###
## ComprobarLogin OK
POST http://localhost:8090/api/usuarios/login HTTP/1.1
Content-Type: application/json

{
    "nickname": "joserra",
    "password": "Passwordjoserra@1"


}




###
## getAllEmpresas
GET http://localhost:8090/api/v1/empresa HTTP/1.1
Content-Type: application/json

###
## getAllEmpresasById
GET http://localhost:8090/api/v1/empresa/2/info HTTP/1.1
Content-Type: application/json

###
## deleteEmpresa

DELETE http://localhost:8090/api/v1/empresa/ HTTP/1.1
Content-Type: application/json







###
# getAllJugadores
GET http://localhost:8090/api/v1/jugadores?sort=idEquipo,asc&sort=dorsal,asc&page=0&size=10 HTTP/1.1
Content-Type: application/json


###
# getAllJugadores
GET http://localhost:8090/api/v1/jugadores?filter=idEquipo:val&sort=idEquipo,asc&sort=dorsal,asc&page=0&size=10 HTTP/1.1
Content-Type: application/json


###
# getAllJugadores
GET http://localhost:8090/api/v1/jugadores?filter=idEquipo:val&filter=sueldo>4000000&sort=idEquipo,asc&sort=dorsal,asc&page=0&size=10 HTTP/1.1
Content-Type: application/json






###
## get AllJugadores FILTRO POST
POST http://localhost:8090/api/v1/jugadores HTTP/1.1
Content-Type: application/json

{
    "listaFiltros":[
        {
            "atributo":"sueldo",
            "operacion":">",
            "valor":6100000
        }
    ],
    "page":0,
    "siza":10,
    "sort":[
        "idEquipo,asc",
        "dorsal,asc"
    ]
}


###
## getAllJugadores CON IGUALDAD
GET http://localhost:8090/api/v1/jugadores?filter=idEquipo:val&filter=sueldo;610000&sort=idEquipo,asc&sort=dorsal,asc&page=0&size=10 HTTP/1.1
Content-Type: application/json


###
## getAllJugadores con MAYOR_QUE
GET http://locahost:8090/api/v1/jugadores?filter=sueldo:MAYOR_QUE:6100000&sort=sueldo,asc&page=0&size=10 HTTP/1.1
Content-Type: application/json

###
## getAllJugadores con MAYOR_QUE
GET http://localhost:8080/api/v1/jugadores?filter=sueldo:MAYOR_QUE:610000&sort=sueldo,asc&page=0&size=10 HTTP/1.1
Content-Type: application/json

###
## getAllJugadores con MENOR_QUE
GET http://localhost:8080/api/v1/jugadores?filter=sueldo:MENOR_QUE:610000&sort=sueldo,desc&page=0&size=10 HTTP/1.1
Content-Type: application/json

###
## getAllJugadores con CONTIENE
GET http://localhost:8080/api/v1/jugadores?filter=idEquipo:CONTIENE:val&sort=idEquipo,asc&sort=dorsal,asc&page=0&size=10 HTTP/1.1
Content-Type: application/json

###
## getAllJugadores con IGUAL
GET http://localhost:8080/api/v1/jugadores?filter=idEquipo:IGUAL:val&sort=idEquipo,asc&sort=dorsal,asc&page=0&size=10 HTTP/1.1
Content-Type: application/json

###
## getAllJugadores con CONTIENE e IGUAL
GET http://localhost:8080/api/v1/jugadores?filter=idEquipo:CONTIENE:val&filter=sueldo:IGUAL:610000&sort=idEquipo,asc&sort=dorsal,asc&page=0&size=10 HTTP/1.1
Content-Type: application/json

###
## getAllJugadores FILTRO POST val
POST http://localhost:8080/api/v1/jugadores HTTP/1.1
Content-Type: application/json

{
  "listaFiltros": [
    {
      "atributo": "idEquipo",
      "operacion": "IGUAL",
      "valor": "val"
    },
    {
      "atributo": "sueldo",
      "operacion": "MAYOR_QUE",
      "valor": 6100000
    }
  ],
  "page": 0,
  "size": 10,
  "sort": [
    "idEquipo,asc",
    "dorsal,asc"
  ]
}


###
## getAllPorteros
GET http://localhost:8090/api/v1/porteros HTTP/1.1
Content-Type: application/json


###
## nuevo incorrecto
POST http://localhost:8090/auth/nuevo HTTP/1.1
Content-Type: application/json

{
  "nickname": "prueba",
  "email": "@",
  "password": "a",
  "roles": ["ROLE_ADMIN"]

}

###
## crear nuevo usuario joserra ok
POST http://localhost:8090/auth/nuevo HTTP/1.1
Content-Type: application/json

{
  "nickname": "joseramon",
  "nombre": "Profesor Jose Ramón",
  "email": "joseramon.profesor@gmail.com",
  "password": "NoTeLoDigo@1",
  "roles": ["ROLE_USER"]
}

##Despues de crear el usuario, Ahora nos logeamos y si todo va bien nos dará un token que deberemos copiar para utilizarlo en la siguiente

###
## login ok
POST http://localhost:8090/auth/login HTTP/1.1
Content-Type: application/json

{
  "nickname": "joseramon",
  "password": "NoTeLoDigo@1"
}

##Y volvemos a realizar la operación copiando el token anterior y ya debería ir
###
## getAllPorteros con JWT
GET http://localhost:8090/api/v1/porteros HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqb3NlcmFtb24iLCJpYXQiOjE3NjkwMzMyOTAsImV4cCI6MTc2OTA2OTI5MH0.ByF_p_yR-sT_K40FttnuOtqosdi8lgTVZexCTDCNDPM