
INSERT INTO genero (nombre, descripcion) VALUES 
('Acción', 'Películas con escenas dinámicas y mucha adrenalina'),
('Comedia', 'Películas humorísticas para reír'),
('Drama', 'Historias serias y emocionales'),
('Ciencia Ficción', 'Futuro, espacio y tecnología avanzada'),
('Terror', 'Películas de miedo y suspenso'),
('Romance', 'Historias de amor y pasión'),
('Aventura', 'Viajes y experiencias emocionantes'),
('Animación', 'Películas realizadas con técnicas de animación'),
('Fantasía', 'Mundos imaginarios y seres mágicos'),
('Documental', 'Películas basadas en hechos reales');


INSERT INTO director (nombre, nacionalidad, fecha_nacimiento) VALUES
('Christopher Nolan', 'Británico', '1970-07-30'),
('Quentin Tarantino', 'Estadounidense', '1963-03-27'),
('Steven Spielberg', 'Estadounidense', '1946-12-18'),
('Martin Scorsese', 'Estadounidense', '1942-11-17'),
('Pedro Almodóvar', 'Español', '1949-09-25'),
('James Cameron', 'Canadiense', '1954-08-16'),
('Tim Burton', 'Estadounidense', '1958-08-25'),
('Ridley Scott', 'Británico', '1937-11-30'),
('Guillermo del Toro', 'Mexicano', '1964-10-09'),
('Hayao Miyazaki', 'Japonés', '1941-01-05'),
('Francis Ford Coppola', 'Estadounidense', '1939-04-07'),
('Alfred Hitchcock', 'Británico', '1899-08-13'),
('Stanley Kubrick', 'Estadounidense', '1928-07-26'),
('George Lucas', 'Estadounidense', '1944-05-14'),
('Clint Eastwood', 'Estadounidense', '1930-05-31'),
('David Fincher', 'Estadounidense', '1962-08-28'),
('Peter Jackson', 'Neozelandés', '1961-10-31'),
('John Lasseter', 'Estadounidense', '1957-01-12'),
('Wes Anderson', 'Estadounidense', '1969-05-01'),
('Alejandro González Iñárritu', 'Mexicano', '1963-08-15');



INSERT INTO usuario (nombre, email, username) VALUES
('Ana García López', 'ana.garcia@email.com', 'anag'),
('Carlos Méndez Ruiz', 'carlos.mendez@email.com', 'carlosm'),
('María Rodríguez Santos', 'maria.rodriguez@email.com', 'mariar'),
('Pedro Martínez Gómez', 'pedro.martinez@email.com', 'pedrom'),
('Laura Sánchez Pérez', 'laura.sanchez@email.com', 'lauras'),
('David Fernández Castro', 'david.fernandez@email.com', 'davidf'),
('Elena Torres Navarro', 'elena.torres@email.com', 'elenat'),
('Javier Ruiz Díaz', 'javier.ruiz@email.com', 'javierr'),
('Sofía Herrera Molina', 'sofia.herrera@email.com', 'sofiah'),
('Daniel Castro Romero', 'daniel.castro@email.com', 'danielc'),
('Carmen Vargas Gil', 'carmen.vargas@email.com', 'carmenv'),
('Álvaro Jiménez Ortega', 'alvaro.jimenez@email.com', 'alvaroj'),
('Patricia Moreno Vega', 'patricia.moreno@email.com', 'patriciam'),
('Roberto Navarro Blanco', 'roberto.navarro@email.com', 'roberton'),
('Isabel Díaz Medina', 'isabel.diaz@email.com', 'isabeld'),
('Francisco Serrano Cruz', 'francisco.serrano@email.com', 'franciscos'),
('Beatriz Romero Sánchez', 'beatriz.romero@email.com', 'beatrizr'),
('Miguel Ángel Torres', 'miguel.torres@email.com', 'miguelat'),
('Cristina Molina Ruiz', 'cristina.molina@email.com', 'cristinam'),
('José Luis Herrera', 'jose.herrera@email.com', 'joseluis'),
('Teresa Castro Méndez', 'teresa.castro@email.com', 'teresac'),
('Alejandro Vega Díaz', 'alejandro.vega@email.com', 'alejandrov'),
('Nuria Ortega Martínez', 'nuria.ortega@email.com', 'nuriao'),
('Manuel Blanco Sánchez', 'manuel.blanco@email.com', 'manuelb'),
('Raquel Medina Torres', 'raquel.medina@email.com', 'raquelm'),
('Sergio Gil Rodríguez', 'sergio.gil@email.com', 'sergiog'),
('Olga Cruz Herrera', 'olga.cruz@email.com', 'olgac'),
('Rubén Vega Castro', 'ruben.vega@email.com', 'rubenv'),
('Adriana Méndez Blanco', 'adriana.mendez@email.com', 'adrianam'),
('Marcos Ruiz Ortega', 'marcos.ruiz@email.com', 'marcosr');


INSERT INTO pelicula (titulo, director_id, genero_id, año, duracion_min, sinopsis) VALUES
('Origen', 1, 4, 2010, 148, 'Un ladrón que roba secretos corporativos mediante el uso de tecnología para compartir sueños.'),
('El caballero oscuro', 1, 1, 2008, 152, 'Batman se enfrenta al Joker, un criminal sádico que amenaza Gotham City.'),
('Interestelar', 1, 4, 2014, 169, 'Un grupo de exploradores viaja a través de un agujero de gusano en el espacio.'),
('Memento', 1, 3, 2000, 113, 'Un hombre con pérdida de memoria a corto plazo intenta encontrar al asesino de su esposa.'),
('El origen del planeta de los simios', 1, 4, 2011, 105, 'Un científico desarrolla un tratamiento que da inteligencia a los simios.'),
('Pulp Fiction', 2, 1, 1994, 154, 'Las vidas de dos asesinos a sueldo, un boxeador y un par de bandidos se entrelazan.'),
('Kill Bill: Volumen 1', 2, 1, 2003, 111, 'Una asesina se despierta de un coma y busca vengarse de su antiguo jefe.'),
('Django Desencadenado', 2, 1, 2012, 165, 'Un esclavo liberado ayuda a un cazarrecompensas a encontrar a unos criminales.'),
('Érase una vez en Hollywood', 2, 3, 2019, 161, 'Un actor de televisión y su doble intentan triunfar en Hollywood en 1969.'),
('Los odiosos ocho', 2, 1, 2015, 168, 'Ocho desconocidos quedan atrapados en una posada durante una tormenta de nieve.'),
('Parque Jurásico', 3, 4, 1993, 127, 'Un parque temático con dinosaurios clonados se descontrola.'),
('La lista de Schindler', 3, 3, 1993, 195, 'Un empresario alemán salva a judíos durante el Holocausto.'),
('Tiburón', 3, 5, 1975, 124, 'Un tiburón gigante aterroriza una comunidad costera.'),
('E.T. el extraterrestre', 3, 4, 1982, 115, 'Un niño ayuda a un extraterrestre a regresar a su planeta.'),
('Indiana Jones: En busca del arca perdida', 3, 7, 1981, 115, 'Un arqueólogo busca el Arca de la Alianza antes que los nazis.'),
('El lobo de Wall Street', 4, 2, 2013, 180, 'La historia real de Jordan Belfort, un corredor de bolsa corrupto.'),
('Taxi Driver', 4, 3, 1976, 114, 'Un veterano de Vietnam solitario trabaja como taxista nocturno en Nueva York.'),
('Infiltrados', 4, 1, 2006, 151, 'Un policía se infiltra en la mafia mientras un gánster trabaja dentro de la policía.'),
('Goodfellas', 4, 1, 1990, 146, 'La vida de Henry Hill en la mafia neoyorquina.'),
('Casino', 4, 3, 1995, 178, 'La historia de un corredor de apuestas que administra un casino para la mafia.'),
('Todo sobre mi madre', 5, 3, 1999, 101, 'Una mujer viaja a Barcelona para encontrar al padre de su hijo fallecido.'),
('Volver', 5, 3, 2006, 121, 'Tres generaciones de mujeres se enfrentan a la muerte y los secretos familiares.'),
('Mujeres al borde de un ataque de nervios', 5, 2, 1988, 88, 'Una actriz descubre que su amante la ha dejado.'),
('Dolor y gloria', 5, 3, 2019, 113, 'Un director de cine envejecido recuerda su vida y carrera.'),
('La piel que habito', 5, 5, 2011, 120, 'Un cirujano plástico crea una piel resistente tras la muerte de su esposa.'),
('Titanic', 6, 6, 1997, 195, 'Una aristócrata se enamora de un artista humilde a bordo del RMS Titanic.'),
('Avatar', 6, 4, 2009, 162, 'Un marine parapléjico es enviado a la luna Pandora en una misión única.'),
('Terminator 2: El juicio final', 6, 1, 1991, 137, 'Un cyborg es enviado al pasado para proteger a John Connor.'),
('Aliens: El regreso', 6, 4, 1986, 137, 'Ellen Ripley regresa al planeta donde encontró a la criatura alienígena.'),
('El abismo', 6, 4, 1989, 171, 'Una tripulación de una plataforma petrolera encuentra una forma de vida submarina.'),
('Pesadilla antes de Navidad', 7, 8, 1993, 76, 'El rey de Halloween descubre la Navidad y decide celebrarla a su manera.'),
('Eduardo Manostijeras', 7, 3, 1990, 105, 'Un hombre creado artificialmente con tijeras en lugar de manos.'),
('Big Fish', 7, 9, 2003, 125, 'Un hijo intenta descubrir la verdad sobre la vida exagerada de su padre.'),
('Charlie y la fábrica de chocolate', 7, 8, 2005, 115, 'Un niño pobre gana un tour por una fábrica de chocolate misteriosa.'),
('Beetlejuice', 7, 2, 1988, 92, 'Una pareja de fantasmas contrata a un bioexorcista para ahuyentar a los nuevos dueños.'),
('Gladiator', 8, 1, 2000, 155, 'Un general romano traicionado busca venganza contra el corrupto emperador.'),
('Alien: el octavo pasajero', 8, 5, 1979, 117, 'La tripulación de una nave espacial investiga una señal de socorro y encuentra un alienígena.'),
('Blade Runner', 8, 4, 1982, 117, 'Un blade runner debe encontrar y retirar a cuatro replicantes fugados.'),
('Thelma y Louise', 8, 1, 1991, 130, 'Dos amigas emprenden un viaje por carretera que cambia sus vidas para siempre.'),
('El reino de los cielos', 8, 1, 2005, 144, 'Un herrero francés defiende Jerusalén durante las Cruzadas.'),
('El laberinto del fauno', 9, 9, 2006, 118, 'Una niña descubre un laberinto mágico durante la posguerra española.'),
('La forma del agua', 9, 6, 2017, 123, 'Una mujer muda se enamora de una criatura anfibia en un laboratorio secreto.'),
('El espinazo del diablo', 9, 5, 2001, 106, 'Un niño llega a un orfanato donde ocurren sucesos sobrenaturales.'),
('Pacific Rim', 9, 1, 2013, 131, 'Pilotos controlan robots gigantes para luchar contra monstruos marinos.'),
('Cronos', 9, 5, 1993, 94, 'Un anciano encuentra un dispositivo que otorga la eterna juventud.'),
('El viaje de Chihiro', 10, 8, 2001, 125, 'Una niña queda atrapada en un mundo de espíritus y debe trabajar para liberar a sus padres.'),
('Mi vecino Totoro', 10, 8, 1988, 86, 'Dos hermanas se mudan al campo y conocen a criaturas del bosque.'),
('La princesa Mononoke', 10, 8, 1997, 133, 'Un joven príncipe se involucra en la lucha entre los dioses del bosque y los humanos.'),
('El castillo ambulante', 10, 8, 2004, 119, 'Una joven es convertida en anciana por una bruja y busca la ayuda de un mago.'),
('El viento se levanta', 10, 3, 2013, 126, 'La vida de Jiro Horikoshi, diseñador de aviones de combate japoneses.'),
('El padrino', 11, 3, 1972, 175, 'El patriarca de una familia de la mafia transfiere el control a su hijo reacio.'),
('Apocalypse Now', 11, 3, 1979, 147, 'Un capitán del ejército debe encontrar y asesinar a un coronel renegado en Vietnam.'),
('El padrino: Parte II', 11, 3, 1974, 202, 'La saga de la familia Corleone continúa, mostrando el ascenso de Vito y la caída de Michael.'),
('La conversación', 11, 3, 1974, 113, 'Un vigilante de vigilancia cree que una pareja que está grabando será asesinada.'),
('Drácula de Bram Stoker', 11, 5, 1992, 128, 'Conde Drácula se muda de Transilvania a Inglaterra en busca de sangre nueva.'),
('Psicosis', 12, 5, 1960, 109, 'Una secretaria roba dinero y se refugia en un motel regentado por un hombre problemático.'),
('Vértigo', 12, 3, 1958, 128, 'Un detective con vértigo investiga el misterioso comportamiento de la esposa de un amigo.'),
('Los pájaros', 12, 5, 1963, 119, 'Una rica socialite persigue a un hombre a una pequeña ciudad donde los pájaros atacan.'),
('La ventana indiscreta', 12, 3, 1954, 112, 'Un fotógrafo confinado a una silla de ruedas espía a sus vecinos y sospecha de un asesinato.'),
('Con la muerte en los talones', 12, 1, 1959, 136, 'Un hombre es perseguido por un avión y se encuentra con una misteriosa rubia.'),
('2001: Una odisea del espacio', 13, 4, 1968, 149, 'La humanidad encuentra un misterioso monolito que afecta la evolución humana.'),
('El resplandor', 13, 5, 1980, 146, 'Un escritor acepta un trabajo de cuidador en un hotel aislado durante el invierno.'),
('La naranja mecánica', 13, 4, 1971, 136, 'Un delincuente juvenil es sometido a un experimento psicológico para curar su violencia.'),
('Senderos de gloria', 13, 3, 1957, 88, 'Un coronel defiende a tres soldados acusados de cobardía durante la Primera Guerra Mundial.'),
('Eyes Wide Shut', 13, 3, 1999, 159, 'Un médico de Manhattan se embarca en un extraño viaje sexual tras una confesión de su esposa.'),
('Star Wars: Episodio IV - Una nueva esperanza', 14, 4, 1977, 121, 'Luke Skywalker se une a la Alianza Rebelde para destruir la Estrella de la Muerte.'),
('Star Wars: Episodio V - El Imperio contraataca', 14, 4, 1980, 124, 'Luke Skywalker entrena con Yoda mientras sus amigos son perseguidos por el Imperio.'),
('Indiana Jones y el templo maldito', 14, 7, 1984, 118, 'Indiana Jones busca una piedra mística en la India.'),
('American Graffiti', 14, 2, 1973, 110, 'Un grupo de adolescentes pasa su última noche de verano antes de la universidad.'),
('THX 1138', 14, 4, 1971, 86, 'Un hombre y una mujer se rebelan contra su sociedad controlada en el futuro.'),
('Million Dollar Baby', 15, 3, 2004, 132, 'Un entrenador de boxeo reacio entrena a una joven boxeadora decidida.'),
('Sin perdón', 15, 1, 1992, 130, 'Un pistolero retirado vuelve a la acción para vengar a una prostituta maltratada.'),
('Gran Torino', 15, 3, 2008, 116, 'Un veterano de la guerra de Corea se hace amigo de su vecino hmong adolescente.'),
('Cazador blanco, corazón negro', 15, 3, 1990, 112, 'Un director de cine viaja a África para filmar una película y se obsesiona con cazar un elefante.'),
('Mystic River', 15, 3, 2003, 138, 'La vida de tres amigos de la infancia se ve afectada cuando la hija de uno es asesinada.'),
('El club de la lucha', 16, 1, 1999, 139, 'Un oficinista insomne y un vendedor de jabón forman un club de lucha subterráneo.'),
('Seven', 16, 3, 1995, 127, 'Dos detectives investigan una serie de asesinatos relacionados con los siete pecados capitales.'),
('La red social', 16, 3, 2010, 120, 'La historia de la creación de Facebook y las batallas legales que siguieron.'),
('Perdida', 16, 3, 2014, 149, 'Un escritor se obsesiona con encontrar a su esposa desaparecida.'),
('Zodiac', 16, 3, 2007, 157, 'Un caricaturista se obsesiona con atrapar al asesino del Zodiaco.'),
('El señor de los anillos: La comunidad del anillo', 17, 9, 2001, 178, 'Un hobbit hereda un anillo poderoso y debe destruirlo en el Monte del Destino.'),
('El señor de los anillos: Las dos torres', 17, 9, 2002, 179, 'Mientras Frodo y Sam se acercan a Mordor, la Compañía se separa.'),
('El señor de los anillos: El retorno del rey', 17, 9, 2003, 201, 'Frodo y Sam llegan a Mordor mientras Aragorn lidera la batalla final.'),
('King Kong', 17, 7, 2005, 187, 'Una tripulación de filmación viaja a una isla misteriosa y encuentra un gorila gigante.'),
('El hobbit: Un viaje inesperado', 17, 9, 2012, 169, 'Bilbo Bolsón se une a una compañía de enanos para recuperar su hogar.'),
('Toy Story', 18, 8, 1995, 81, 'Los juguetes de un niño cobran vida cuando él no está presente.'),
('Buscando a Nemo', 18, 8, 2003, 100, 'Un pez payaso sobreprotector busca a su hijo perdido en el océano.'),
('Cars', 18, 8, 2006, 117, 'Un coche de carreras arrogante aprende el valor de la amistad y la familia.'),
('Ratatouille', 18, 8, 2007, 111, 'Una rata que ama cocinar se alía con un joven chef en París.'),
('Wall-E', 18, 8, 2008, 98, 'Un robot de limpieza en la Tierra deshabitada se enamora de otro robot.'),
('El gran hotel Budapest', 19, 2, 2014, 99, 'Las aventuras de un conserje y su protegido en un hotel europeo entre guerras.'),
('Los Tenenbaum', 19, 2, 2001, 110, 'Los miembros disfuncionales de una familia de genios se reúnen.'),
('Moonrise Kingdom', 19, 6, 2012, 94, 'Dos jóvenes enamorados huyen de su pueblo natal, provocando una búsqueda.'),
('Fantastic Mr. Fox', 19, 8, 2009, 87, 'Un zorro astuto roba comida de tres granjeros mezquinos.'),
('Isla de perros', 19, 8, 2018, 101, 'Un niño busca a su perro en una isla de basura donde están todos los caninos.'),
('Birdman', 20, 2, 2014, 119, 'Un actor famoso intenta revivir su carrera en Broadway.'),
('El renacido', 20, 3, 2015, 156, 'Un hombre es dejado por muerto después de un ataque de oso y busca venganza.'),
('Babel', 20, 3, 2006, 143, 'Tragedias interconectadas ocurren en Marruecos, Japón y México.'),
('Amores perros', 20, 3, 2000, 154, 'Tres historias conectadas por un accidente automovilístico en Ciudad de México.'),
('21 gramos', 20, 3, 2003, 124, 'Un accidente reúne a un matemático, una madre y un exconvicto.');


INSERT INTO valoracion (pelicula_id, usuario_id, puntuacion, comentario, likes) VALUES
(1, 1, 5, 'Increíble película, Nolan es un genio!', 12),
(1, 2, 4, 'Muy buena, aunque la trama puede ser confusa.', 5),
(2, 3, 5, 'Heath Ledger como el Joker es lo mejor que he visto.', 25),
(6, 4, 5, 'Clásico del cine moderno, diálogos brillantes.', 18),
(7, 5, 3, 'Divertida pero demasiado violenta para mi gusto.', 3),
(11, 6, 4, 'Los dinosaurios siguen siendo impresionantes.', 15),
(16, 7, 5, 'Emocionante de principio a fin, una obra maestra.', 22),
(21, 8, 4, 'Almodóvar en su mejor momento.', 9),
(26, 9, 5, 'La historia de amor más épica del cine.', 30),
(31, 10, 2, 'No entiendo el hype, me pareció aburrida.', 1),
(36, 11, 5, 'Scorsese es el rey del cine de gánsteres.', 17),
(41, 12, 4, 'Buena adaptación del cómic.', 8),
(46, 13, 5, 'Spielberg demuestra por qué es el mejor.', 21),
(51, 14, 3, 'Interesante pero demasiado larga.', 4),
(56, 15, 5, 'Del Toro crea mundos mágicos como nadie.', 19),
(61, 16, 4, 'Miyazaki es un artista visual único.', 14),
(66, 17, 5, 'El mejor thriller psicológico de la historia.', 27),
(71, 18, 4, 'Kubrick era un visionario.', 11),
(76, 19, 5, 'Lucas cambió el cine para siempre con esta.', 33),
(81, 20, 3, 'Divertida pero olvidable.', 2);




